services:
  postgres:
    image: postgres:15-alpine
    container_name: gading_new_town_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gading_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
